# 
# Small makefile for Saisie
#

CC=g++
main: main.o
	$(CC) -o main main.o  C:\msys64\mingw64\lib\libfreeglut.a C:\Windows\System32\opengl32.dll C:\msys64\mingw64\lib\libglew32.a C:\msys64\mingw64\lib\libglu32.a -larmadillo
all: saisieinteractive
